### PR TITLE
Fail-safe check on RSA

### LINKED ISSUE #75: Missing hash function validation in RSA-PSS signatures
RSA-PSS Sign() function ignores the boolean returned from rs.alg.hashFunc(). While the current code returns a valid hash function for RSA, the code is brittle and error-prone. The boolean return should be validated to ensure that there is a recognized hash function (check for a true value) and there is a hash function (hash = crypto.Hash is not zero).

File: go-cose/rsa.go.

### PR DESCRIPTION
**Pull request by shizhMSFT**
Although `rs.alg.hashFunc()` never returns `false`, this PR makes it sound even if we have programming errors.

Fixes #75

### CODE REVIEW

File: rsa.go [hunk 1]
```diff
@@ -49,7 +52,10 @@ func (rv *rsaVerifier) Algorithm() Algorithm {
 //
 // Reference: https://datatracker.ietf.org/doc/html/rfc8152#section-8
 func (rv *rsaVerifier) Verify(digest []byte, signature []byte) error {
-	hash, _ := rv.alg.hashFunc()
+	hash, ok := rv.alg.hashFunc()
+	if !ok {
+		return ErrVerification
```
Comment (thomas-fossati) [inline rsa.go:57]: Maybe this could be more specific on the kind of error, i.e., `ErrInvalidAlgorithm`

Comment (shizhMSFT) [reply rsa.go:57]: Updated to `ErrInvalidAlgorithm`

**Review by thomas-fossati — APPROVED** [review]
